security:
    providers:
        fos_user_bundle:
            id: fos_user.user_manager

    encoders: 
        FOS\UserBundle\Model\UserInterface: sha512
        
    firewalls:
        public:
            pattern:    ^/
            form_login:
                provider: fos_user_bundle
                csrf_provider: form.csrf_provider
            fos_facebook:
                  app_url: "http://apps.facebook.com/abmundi/"
                  server_url: "http://localhost/fosfbfix/web/app_dev.php/"
            logout: 
                  handlers: ["fos_facebook.logout_handler"]
            anonymous: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
         
    access_control:
        - { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY] } # This is the route secured with fos_facebook
        - { path: ^/.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]