services:
    my.facebook.user:
        class: FFF\UserBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"

security:
    factories:
        - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"
        
    providers:
        fos_user_bundle:
            id: fos_user.user_manager
        my_fos_facebook_provider:
            id: my.facebook.user
        chainprovider:
            providers: [fos_user_bundle, my_fos_facebook_provider]

    encoders: 
        FOS\UserBundle\Model\UserInterface: sha512
        
    firewalls:
        public:
            pattern:    ^/
            fos_facebook:
                app_url: "http://apps.facebook.com/abmundi/"
                server_url: "http://localhost/fosfbfix/web/app_dev.php/"
                login_path: /login
                check_path: /loginFb
                default_target_path: /
                provider: my_fos_facebook_provider
            form_login:
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
                provider: fos_user_bundle
            logout: true
            anonymous: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
         
    access_control:
        - { path: ^/.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/facebook/, role: [ROLE_FACEBOOK] }
        - { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY] } # This is the route secured with fos_facebook
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]